// flow-typed signature: 7105dc63f2cebac7c569207104646a74
// flow-typed version: <<STUB>>/lit-html_v0.9.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lit-html'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lit-html' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lit-html/lib/async-append' {
  declare module.exports: any;
}

declare module 'lit-html/lib/async-replace' {
  declare module.exports: any;
}

declare module 'lit-html/lib/lit-extended' {
  declare module.exports: any;
}

declare module 'lit-html/lib/repeat' {
  declare module.exports: any;
}

declare module 'lit-html/lib/shady-render' {
  declare module.exports: any;
}

declare module 'lit-html/lib/toggle' {
  declare module.exports: any;
}

declare module 'lit-html/lib/unsafe-html' {
  declare module.exports: any;
}

declare module 'lit-html/lib/until' {
  declare module.exports: any;
}

declare module 'lit-html/lit-html' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lit-html/lib/async-append.js' {
  declare module.exports: $Exports<'lit-html/lib/async-append'>;
}
declare module 'lit-html/lib/async-replace.js' {
  declare module.exports: $Exports<'lit-html/lib/async-replace'>;
}
declare module 'lit-html/lib/lit-extended.js' {
  declare module.exports: $Exports<'lit-html/lib/lit-extended'>;
}
declare module 'lit-html/lib/repeat.js' {
  declare module.exports: $Exports<'lit-html/lib/repeat'>;
}
declare module 'lit-html/lib/shady-render.js' {
  declare module.exports: $Exports<'lit-html/lib/shady-render'>;
}
declare module 'lit-html/lib/toggle.js' {
  declare module.exports: $Exports<'lit-html/lib/toggle'>;
}
declare module 'lit-html/lib/unsafe-html.js' {
  declare module.exports: $Exports<'lit-html/lib/unsafe-html'>;
}
declare module 'lit-html/lib/until.js' {
  declare module.exports: $Exports<'lit-html/lib/until'>;
}
declare module 'lit-html/lit-html.js' {
  declare module.exports: $Exports<'lit-html/lit-html'>;
}
